Feature/hybrid component
ellipticaljs/paper-autocomplete pull request #69
Opened 2017-05-17 08:26 UTC by ajbarriosleon

- New hybrid component adaptation.
- Removed Polymer 1.X legacy code according to Polymer hybrid upgrade guide.
- Tests suite passed.
- Demo code simplified and better reallocated.
- Upgraded dependencies to Polymer 2.0.

2017-05-22 11:22 UTC, jhuesos commented
When I tried to test your branch I saw several big issues.

Please make sure that the component still works with Polymer 1.x and Polymer 2.x. If it doesn't work anymore with Polymer 1.x, we can maybe push a new major version with breaking changes. We need to review this change more.

2017-05-22 13:52 UTC, jhuesos commented
Please do not re-style the files, **maintain the current style**. There are hundreds of lines changed just because of style changes. Please revert all those changes as well.

Unless there is clearly an error in the current style. Try to only update the necessary lines to make this feature to work.

2017-05-23 08:07 UTC, ajbarriosleon commented
Hi. We just changed some files to solve:
- Polymer 1.x compatibility issues.
-Clear button now visibility.
- Current style format

2017-05-23 08:40 UTC, jhuesos commented on paper-autocomplete-suggestions.html
> +        max-height: 2G2px;
2G2px? I think this is an error

2017-05-23 08:42 UTC, jhuesos commented on paper-autocomplete-suggestions.html
> +  <script>
It seems the whole script tag has been formatted because it appears that all lines has changed. Can you revert this formatting? Thanks

2017-05-23 08:43 UTC, jhuesos requested changes
Please revert all unnecessary format changes. Then I will do the rest of the review.

Only push the necessary changes to make this work. Respect the current formatting.

2017-05-23 08:43 UTC, jhuesos commented on paper-autocomplete.html
> +  <script>
Same here, revert all formatting changes.

2017-05-23 09:09 UTC, jhuesos commented
I just found another visual issue, padding inside the elements is gone:

BEFORE THIS PR
![0932c0ec-3fa8-11e7-944a-879c9b5a681c](https://cloud.githubusercontent.com/assets/339609/26346931/219c0b70-3fa8-11e7-87ba-7ecd83bfff03.jpg)

NEW VERSION
![paper-autocomplete documentation 2017-05-23 11-06-44](https://cloud.githubusercontent.com/assets/339609/26346918/1742ff3a-3fa8-11e7-9155-3aba1fde3ef4.jpg)

@ajbarriosleon Can you confirm if you see this issue as well?

2017-05-24 05:42 UTC, ajbarriosleon commented
Hi. We just pushed some commits to fix these problems:
- Padding visual issue on Polymer 2.x
- Old indentation adaptation

I hope it's ok for you. Thank you.

2017-05-24 07:11 UTC, jhuesos commented
I have found so far, two other regressions which need to be investigated more:
- The clear button, when it is clicked, it should clear the input field and focus the element. That is how it works with Polymer 1.x but not in Polymer 2.x. In the following video you can see the comparison between v1.x and v2.x. First it shows how it behaves with Polymer 1.x and second tab is with polymer 2.x

![clear-button-regression](https://cloud.githubusercontent.com/assets/339609/26390741/2226eafc-4060-11e7-8c30-301bed947687.gif)

- The style in the custom template is also wrong. The following two screenshots show how it looks with Polymer 1.x and with Polymer 2.x

**Polymer 1.x**
![paper-autocomplete demo 2017-05-24 09-07-55](https://cloud.githubusercontent.com/assets/339609/26390862/a402b678-4060-11e7-8081-31dc171683b3.jpg)

**Polymer 2.x**
![paper-autocomplete demo 2017-05-24 09-07-35](https://cloud.githubusercontent.com/assets/339609/26390854/9c10d2e2-4060-11e7-9b20-5acf1dc3f9dc.jpg)

Please investigate these issues first. And please, **make sure you do proper testing!!!!** Compare the behavior with Polymer 1.x and Polymer 2.x and make sure there are no regressions. If some of the regressions are impossible to fix because of changes between ShadowDom v0 and v1, let's discuss what should we do about those.

2017-05-24 07:50 UTC, jhuesos commented
@ajbarriosleon More regressions issues:

![paper-autocomplete documentation 2017-05-24 09-35-22](https://cloud.githubusercontent.com/assets/339609/26392184/0116e8ac-4066-11e7-9d6a-43265e7351b7.jpg)

In Internet Explorer 11, things are worse:
- With polymer 1.x, nothings seem to work (Can you confirm this?)

![screen shot 2017-05-24 at 09 47 05](https://cloud.githubusercontent.com/assets/339609/26392224/26fcc488-4066-11e7-9780-91c7f6d7f880.png)

- With Polymer 2.x, the component works but it has at least one small regression: now it shows again the double clear button

![screen shot 2017-05-24 at 09 49 42](https://cloud.githubusercontent.com/assets/339609/26392288/5a61672a-4066-11e7-91b3-03e5184ffa8d.png)

2017-05-26 11:25 UTC, ajbarriosleon commented
Hey @jhuesos We have fixed these things:
- Clear button on IE11.
- Focus when clear is clicked.
- Warning in console for [[accounts]] binding.
- Demo is now aligned correctly.
- Styles on both version of Polymer
- Tested on Chrome, Mozilla, Safari.

Things we want to **highlight**:

- The console warning of Polymer.Templatizer has been inherited from master. Apparently, the documentation process for iron-pages fails but it works on the component.
- There are a lot of issues about the webcomponents polyfills, shadow-dom or Polymer 2.0 with IE11. We consider to merge in a new **2.0-preview** branch if you agree with this PR and then, we could open a new branch called IE11-compatibility for instance, to add it to our next backlog. Most used browsers work fine, so we cover a big percent right now and we can update our current backlog 
backlog.

Thank you!

2017-05-28 12:52 UTC, jhuesos commented
@ajbarriosleon sounds like a good plan. Let's merge to 2.0-preview and continue there. I will try to take a look today and tomorrow, so we can merge and close this PR. Good job!

2017-05-29 06:13 UTC, ajbarriosleon commented
Perfect!

2017-05-29 16:44 UTC, jhuesos approved these changes

2017-05-29 16:44 UTC, merged